# Generated by Django 3.0.3 on 2020-02-08 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Catalog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=50, null=True, verbose_name="name of image"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        max_length=50, null=True, verbose_name="location taken"
                    ),
                ),
                (
                    "year",
                    models.IntegerField(null=True, verbose_name="year taken"),
                ),
                (
                    "path",
                    models.CharField(
                        default="path/to/placeholder.png",
                        max_length=200,
                        verbose_name="path to file",
                    ),
                ),
            ],
        ),
    ]
