# Generated by Django 3.0.3 on 2020-02-08 02:12

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("photos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prints",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("sml", "Small"),
                            ("med", "Medium"),
                            ("lrg", "large"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "print_cost",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("time_placed", models.DateTimeField()),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50)),
                ("primary_phone", models.CharField(max_length=20)),
                ("address_line_one", models.CharField(max_length=100)),
                (
                    "address_line_two",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("city", models.CharField(max_length=20)),
                ("state_or_region", models.CharField(max_length=20)),
                ("postal_code", models.IntegerField()),
                ("country", models.CharField(max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "created"),
                            ("shipped", "shipped"),
                            ("fulfilled", "fulfilled"),
                            ("rejected", "rejected"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "photo_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="photos.Catalog",
                    ),
                ),
                (
                    "print_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="checkout.Prints",
                    ),
                ),
            ],
        ),
    ]
